packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@orpc/server': ^1.13.4
  '@orpc/client': ^1.13.4
  '@orpc/openapi': ^1.13.4
  '@orpc/zod': ^1.13.4
  '@orpc/json-schema': ^1.13.4
  '@orpc/tanstack-query': ^1.13.4
  "@orpc/experimental-pino": ^1.13.4
  "@orpc/contract": ^1.13.4
  better-auth: ^1.4.17
  dotenv: ^17.2.2
