packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@orpc/server': ^1.13.6
  '@orpc/client': ^1.13.6
  '@orpc/openapi': ^1.13.6
  '@orpc/zod': ^1.13.6
  '@orpc/json-schema': ^1.13.6
  '@orpc/tanstack-query': ^1.13.6
  "@orpc/experimental-pino": ^1.13.6
  "@orpc/contract": ^1.13.6
  better-auth: ^1.5.5
  dotenv: ^17.2.2
