/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as marketingIndexRouteImport } from './routes/(marketing)/index'
import { Route as ProtectedAppIndexRouteImport } from './routes/_protected/app/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as ApiUploadCloudflareRouteImport } from './routes/api/upload/cloudflare'
import { Route as ApiUploadBackblazeRouteImport } from './routes/api/upload/backblaze'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingIndexRoute = marketingIndexRouteImport.update({
  id: '/(marketing)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAppIndexRoute = ProtectedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any)
const ApiUploadCloudflareRoute = ApiUploadCloudflareRouteImport.update({
  id: '/api/upload/cloudflare',
  path: '/api/upload/cloudflare',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadBackblazeRoute = ApiUploadBackblazeRouteImport.update({
  id: '/api/upload/backblaze',
  path: '/api/upload/backblaze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof marketingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/upload/backblaze': typeof ApiUploadBackblazeRoute
  '/api/upload/cloudflare': typeof ApiUploadCloudflareRoute
  '/login': typeof AuthLoginIndexRoute
  '/app': typeof ProtectedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof marketingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/upload/backblaze': typeof ApiUploadBackblazeRoute
  '/api/upload/cloudflare': typeof ApiUploadCloudflareRoute
  '/login': typeof AuthLoginIndexRoute
  '/app': typeof ProtectedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/(marketing)/': typeof marketingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/upload/backblaze': typeof ApiUploadBackblazeRoute
  '/api/upload/cloudflare': typeof ApiUploadCloudflareRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_protected/app/': typeof ProtectedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/upload/backblaze'
    | '/api/upload/cloudflare'
    | '/login'
    | '/app'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/upload/backblaze'
    | '/api/upload/cloudflare'
    | '/login'
    | '/app'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/(marketing)/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/upload/backblaze'
    | '/api/upload/cloudflare'
    | '/_auth/login/'
    | '/_protected/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  marketingIndexRoute: typeof marketingIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiUploadBackblazeRoute: typeof ApiUploadBackblazeRoute
  ApiUploadCloudflareRoute: typeof ApiUploadCloudflareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/': {
      id: '/(marketing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/app/': {
      id: '/_protected/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof ProtectedAppIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/upload/cloudflare': {
      id: '/api/upload/cloudflare'
      path: '/api/upload/cloudflare'
      fullPath: '/api/upload/cloudflare'
      preLoaderRoute: typeof ApiUploadCloudflareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/backblaze': {
      id: '/api/upload/backblaze'
      path: '/api/upload/backblaze'
      fullPath: '/api/upload/backblaze'
      preLoaderRoute: typeof ApiUploadBackblazeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAppIndexRoute: typeof ProtectedAppIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAppIndexRoute: ProtectedAppIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  marketingIndexRoute: marketingIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiUploadBackblazeRoute: ApiUploadBackblazeRoute,
  ApiUploadCloudflareRoute: ApiUploadCloudflareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
